const temp = {
  1: require('./icons/icon11.png'),
  2: require('./icons/icon12.png'),
  3: require('./icons/icon13.png'),
  4: require('./icons/icon14.png'),
  5: require('./icons/icon15.png'),
  6: require('./icons/icon16.png'),
  7: require('./icons/icon17.png'),
  8: require('./icons/icon18.png'),
  9: require('./icons/icon20.png'),
  10: require('./icons/icon21.png'),
  11: require('./icons/icon22.png'),
  12: require('./icons/icon23.png'),
  13: require('./icons/icon24.png'),
  14: require('./icons/icon25.png'),
  15: require('./icons/icon26.png'),
  16: require('./icons/icon27.png'),
  17: require('./icons/icon28.png'),
  18: require('./icons/icon29.png'),
  19: require('./icons/icon30.png'),
  20: require('./icons/icon35.png'),
  21: require('./icons/icon36.png'),
  22: require('./icons/icon37.png'),
  23: require('./icons/icon38.png'),
  24: require('./icons/icon39.png'),
};
export default temp;
